### ISSUE TITLE
1080p Remakes

### ISSUE THREAD

**Issue by lnjX** [DuraPhilms/unknown6656.com-harrypotter#1]
Ich habe bisher von den Teilen 1-6 (PvA) ein 1080p Remaster gemacht, waere cool wenn du das mit embedden koenntest.

Du kannst die Teile hier finden:
https://archive.org/details/HPudPvA_1080Rmk

Und hier ist nochmal eine Liste wo es die Teile noch gibt:
https://docs.google.com/spreadsheets/d/1yt13Hg29kKO-DjeY88lLSXUwXFu8cd2emUk9ETnOl1w/pubhtml

**Comment by Unknown6656** [comment]
@InjX Hey, Danke für die Reply..... aus irgendeinem Grund zeigt mir GitHub die Notification erst 3 [!!!] Jahre zu spät an.
Wie ich sehe, habt ihr in der Zwischenzeit euren eigenen Mirror/Hoster aufgesetzt.
Gratulation, die Webseite sieht sehr stark aus!

Ich habe meine Webseite auf Vordermann gebracht, sodass alle alten Parts wieder online sind (inzwischen lautet die URL https://unknown6656.com/harrypotter/).
Ich werde die kommenden Tage euch dort ebenfalls verlinken.

**Comment by lnjX** [comment]
Ist auf jeden Fall lustig nach 3 Jahren nochmal ploetzlich eine Antwort zu bekommen! Vielen dank auch fuer deine Arbeit, wir hatten glaube ich auch ein paar Grafiken von dir verwendet. Unsere Webseite koennte bestimmt auch noch ein paar design-aenderungen vertragen. Wenn du Lust hast irgendwas zu machen / zu verbessern, das repository ist hier zu finden: https://github.com/duraphilms/duraphilms.github.io/

Und wenn du irgendwelche anderen Ideen fuer die domain oder Aehnliches hast, sag einfach mal bescheid. :)

**Comment by lnjX** [comment]
(Wenn du irgendwas von uns verwenden moechtest, nur zu.)

###### Ah und den issue hier mach ich mal zu...

**Comment by Unknown6656** [comment]
@lnjX Haha, ja das kann ich mir vorstellen, dass nach nach 3 Jahren eine Fortführung der Konversation etwas überraschend ist.
Das ist kein Problem, dass ihr euch einige Grafiken geschnappt habt ;)
Ich habe mir ebenso eure thumbnails ungefragt gemopst.

Ich glaube, dass ich einige Ideen für eure Webseite habe, allerdings werde ich mich denen erst in einigen Wochen widmen können (ich zurzeit durch die Universität etc. eingespannt). Die Grundlegenden Punkte wären allerdings:
- mögliche Einbettung von den Coldmirror-Parodien
- Autoplay für den nächsten Part
- Eine Kommentarfunktion für Besucher (evtl. kann man ja die vorhandenen YT-Kommentare scrapen und schon hinzufügen).
- Mehrere kleine Design-Ideen/Überarbeitungen

Etwas unrelated:
Arbeitest du/ihr noch an den 1080p remakes?
Vielleicht kann ich auch noch dazu ein wenig beitragen (Erfahrung mit After Effects und Premiere habe ich noch).

-----

Wenn ich (hoffentlich bald) mehr Zeit haben sollte, dann können wir uns gerne nochmal ausführlicher diesbezüglich besprechen -- von mir aus gerne auch via Discord o.Ä.

**Comment by Unknown6656** [comment]
Addendum: Der Duraphilms-Organisation würde ich gerne joinen, wenn dies möglich ist.
Wir könnten ja eine Repo für Artwork anlegen und dort auch Banner/Bilder/Icons/.... hochladen, welche in anderen Duraphilms-Projekten weiterverwendet werden können.

**Comment by lnjX** [comment]
> Ich glaube, dass ich einige Ideen für eure Webseite habe, allerdings werde ich mich denen erst in einigen Wochen widmen können (ich zurzeit durch die Universität etc. eingespannt). Die Grundlegenden Punkte wären allerdings:

Oh super cool. Macht ja nichts, wenn du erst in einigen Wochen Zeit hast. :)

> * mögliche Einbettung von den Coldmirror-Parodien

Das sollte leicht zu machen sein. Da es da ja keine parts gibt, koennen wir vielleicht einfach eine Playlist mit Ein Stein / Pornokeller / Plastikpokal anlegen.

> * Autoplay für den nächsten Part

Da muss man vermutlich ein bisschen was mit JS machen, wuerde mich freuen, wenn du lust drauf hast! :)

> * Eine Kommentarfunktion für Besucher (evtl. kann man ja die vorhandenen YT-Kommentare scrapen und schon hinzufügen).

Bisher ist die Seite ja komplett static. Kommentare importieren und einfach anzeigen sollte machbar sein. Damit wirklich Leute neue Kommentare schreiben koennen, muesste man da nochmal was dynamisches extra machen und betreiben.

> * Mehrere kleine Design-Ideen/Überarbeitungen

Ja das waere super, gibt vieles was nicht ideal ist und eine Ueberarbeitung vertragen koennte (auch zum Teil technisch).

> Etwas unrelated:
Arbeitest du/ihr noch an den 1080p remakes?
Vielleicht kann ich auch noch dazu ein wenig beitragen (Erfahrung mit After Effects und Premiere habe ich noch).

Ja so ca. einmal im Jahr setze ich mich zwei Tag lang hin und schneide einen Teil. Ich hab dafuer immer [kdenlive](https://kdenlive.org) unter Linux genutzt. Neurdings gibts das auch fuer Windows, weiss aber nicht wie stabil es da laeuft. Wenn du irgendwas da machen moechtest, kann ich dir aber das Material zukommen lassen (HP3 in 4k usw.).


> Wenn ich (hoffentlich bald) mehr Zeit haben sollte, dann können wir uns gerne nochmal ausführlicher diesbezüglich besprechen -- von mir aus gerne auch via Discord o.Ä.

Gerne, Discord nutze ich aktuell nicht, aber Jabber/XMPP, Telegram, Matrix, ... ahh hab dich gerade auf Telegram gefunden ok...

> Addendum: Der Duraphilms-Organisation würde ich gerne joinen, wenn dies möglich ist.
Wir könnten ja eine Repo für Artwork anlegen und dort auch Banner/Bilder/Icons/.... hochladen, welche in anderen Duraphilms-Projekten weiterverwendet werden können.

Hab dich eingeladen, du kannst gerne so ein repo erstellen :)
